CREATE DATABASE car_db;

\c car_db

CREATE TABLE IF NOT EXISTS car
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    car_name VARCHAR,
    brand VARCHAR,
    country VARCHAR,
    price NUMERIC,
    horsepower INTEGER
);

CREATE TABLE IF NOT EXISTS users
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar,
    u_password varchar,
    u_role varchar
);